[versions]
accompanist = "0.33.2-alpha"
agp = "8.2.0-rc02"
cameraX = "1.3.0"
coil = "2.4.0"
commonmark = "0.21.0"
compose = "1.6.0-alpha08"
composeActivity = "1.8.0"
composeCompiler = "1.5.3"
core = "1.12.0"
firebase = "32.5.0"
glance = "1.0.0"
junit = "4.13.2"
koin = "3.5.0"
koinAndroid = "3.5.0"
kotlin = "1.9.10"
kotlinCoroutines = "1.7.3"
kotlinKsp = "1.9.10-1.0.13"
ktor = "2.3.4"
lifecycle = "2.7.0-beta01"
material3 = "1.2.0-alpha10"
room = "2.6.0"

[libraries]
accompanistNavigation = { module = "com.google.accompanist:accompanist-navigation-material", version.ref = "accompanist" }
accompanistPagerIndicators = { module = "com.google.accompanist:accompanist-pager-indicators", version.ref = "accompanist" }
accompanistPermissions = { module = "com.google.accompanist:accompanist-permissions", version.ref = "accompanist" }
accompanistSystemUi = { module = "com.google.accompanist:accompanist-systemuicontroller", version.ref = "accompanist" }
activityX = { module = "androidx.activity:activity-ktx", version.ref = "composeActivity" }
apacheCommonsCodec = "commons-codec:commons-codec:1.15"
appcompat = "androidx.appcompat:appcompat:1.6.1"
barcodeScanning = "com.google.mlkit:barcode-scanning:17.2.0"
biometric = "androidx.biometric:biometric:1.1.0"
camera2 = { module = "androidx.camera:camera-camera2", version.ref = "cameraX" }
camera2Lifecycle = { module = "androidx.camera:camera-lifecycle", version.ref = "cameraX" }
camera2View = { module = "androidx.camera:camera-view", version.ref = "cameraX" }
coil = { module = "io.coil-kt:coil", version.ref = "coil" }
coilCompose = { module = "io.coil-kt:coil-compose", version.ref = "coil" }
commonmarkCore = { module = "org.commonmark:commonmark", version.ref = "commonmark" }
commonmarkLink = { module = "org.commonmark:commonmark-ext-autolink", version.ref = "commonmark" }
commonmarkStrikethrough = { module = "org.commonmark:commonmark-ext-gfm-strikethrough", version.ref = "commonmark" }
commonmarkTables = { module = "org.commonmark:commonmark-ext-gfm-tables", version.ref = "commonmark" }
composeActivity = { module = "androidx.activity:activity-compose", version.ref = "composeActivity" }
composeAnimation = { module = "androidx.compose.animation:animation", version.ref = "compose" }
composeCompiler = { module = "androidx.compose.compiler:compiler", version.ref = "composeCompiler" }
composeMaterial2 = { module = "androidx.compose.material:material", version.ref = "compose" }
composeNavigation = "androidx.navigation:navigation-compose:2.7.5"
composeUi = { module = "androidx.compose.ui:ui", version.ref = "compose" }
composeUiTooling = { module = "androidx.compose.ui:ui-tooling", version.ref = "compose" }
composeUiUtil = { module = "androidx.compose.ui:ui-util", version.ref = "compose" }
core = { module = "androidx.core:core-ktx", version.ref = "core" }
coreSplash = "androidx.core:core-splashscreen:1.0.1"
dataStore = "androidx.datastore:datastore-preferences:1.0.0"
desugar = "com.android.tools:desugar_jdk_libs:2.0.4"
firebaseBom = { module = "com.google.firebase:firebase-bom", version.ref = "firebase" }
firebaseCrashlytics = { module = "com.google.firebase:firebase-crashlytics-ktx" }
firebaseMessaging = { module = "com.google.firebase:firebase-messaging-ktx" }
glanceWidget = { module = "androidx.glance:glance-appwidget", version.ref = "glance" }
googleApiClientAndroid = "com.google.api-client:google-api-client-android:2.2.0"
googleApiClientGson = "com.github.rafakob.google-http-java-client:google-http-client-gson:1.43.0"
googleAuth = "com.google.android.gms:play-services-auth:20.7.0"
googleDrive = "com.google.apis:google-api-services-drive:v3-rev197-1.25.0"
javaxInject = "javax.inject:javax.inject:1"
junit = { module = "junit:junit", version.ref = "junit" }
junit-junit = { module = "junit:junit", version.ref = "junit" }
koinCompose = { module = "io.insert-koin:koin-androidx-compose", version.ref = "koinAndroid" }
koinTest = { module = "io.insert-koin:koin-test", version.ref = "koin" }
koinTestJunit = { module = "io.insert-koin:koin-test-junit4", version.ref = "koin" }
kotlinCoroutines = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "kotlinCoroutines" }
kotlinSerialization = "org.jetbrains.kotlinx:kotlinx-serialization-json:1.6.0"
ktorAuth = { module = "io.ktor:ktor-client-auth", version.ref = "ktor" }
ktorContentNegotiation = { module = "io.ktor:ktor-client-content-negotiation", version.ref = "ktor" }
ktorCore = { module = "io.ktor:ktor-client-core", version.ref = "ktor" }
ktorKotlinSerialization = { module = "io.ktor:ktor-serialization-kotlinx-json", version.ref = "ktor" }
ktorLogging = { module = "io.ktor:ktor-client-logging", version.ref = "ktor" }
ktorOkhttp = { module = "io.ktor:ktor-client-okhttp", version.ref = "ktor" }
lifecycle = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "lifecycle" }
lifecycleCompose = { module = "androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "lifecycle" }
lifecycleComposeRuntime = { module = "androidx.lifecycle:lifecycle-runtime-compose", version.ref = "lifecycle" }
lifecycleLifecycle = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "lifecycle" }
lifecycleProcess = { module = "androidx.lifecycle:lifecycle-process", version.ref = "lifecycle" }
lifecycleSavedstate = { module = "androidx.lifecycle:lifecycle-viewmodel-savedstate", version.ref = "lifecycle" }
lottie = "com.airbnb.android:lottie-compose:5.0.3"
material2 = "com.google.android.material:material:1.10.0"
material3 = { module = "androidx.compose.material3:material3", version.ref = "material3" }
material3Window = { module = "androidx.compose.material3:material3-window-size-class", version.ref = "material3" }
playReview = "com.google.android.play:review:2.0.1"
playReviewKtx = "com.google.android.play:review-ktx:2.0.1"
playServicesCorutines = "org.jetbrains.kotlinx:kotlinx-coroutines-play-services:1.7.3"
playUpdate = "com.google.android.play:app-update:2.1.0"
playUpdateKtx = "com.google.android.play:app-update-ktx:2.1.0"
protobuf = "com.google.protobuf:protobuf-kotlin-lite:3.19.1"
reLinker = "com.getkeepsafe.relinker:relinker:1.4.5"
roomCompiler = { module = "androidx.room:room-compiler", version.ref = "room" }
roomKtx = { module = "androidx.room:room-ktx", version.ref = "room" }
roomRuntime = { module = "androidx.room:room-runtime", version.ref = "room" }
secureStorage = "de.adorsys.android:securestoragelibrary:1.2.4"
securityCrypto = "androidx.security:security-crypto:1.1.0-alpha05"
sharedPrefs = "androidx.preference:preference-ktx:1.2.1"
sqlCipher = "net.zetetic:android-database-sqlcipher:4.5.4"
timber = "com.jakewharton.timber:timber:5.0.1"
webkit = "androidx.webkit:webkit:1.8.0"
workManager = "androidx.work:work-runtime-ktx:2.8.1"

[bundles]
accompanist = [
    "accompanistNavigation",
    "accompanistPagerIndicators",
    "accompanistPermissions",
    "accompanistSystemUi",
]
appCompat = [
    "appcompat",
    "core",
]
barcodeScanner = [
    "barcodeScanning",
    "camera2",
    "camera2Lifecycle",
    "camera2View",
]
coil = [
    "coil",
    "coilCompose",
]
commonmark = [
    "commonmarkCore",
    "commonmarkLink",
    "commonmarkStrikethrough",
    "commonmarkTables",
]
compose = [
    "composeActivity",
    "composeMaterial2",
    "composeNavigation",
    "composeUi",
    "composeUiTooling",
    "composeUiUtil",
    "material2",
    "material3",
    "material3Window",
]
glance = [
    "glanceWidget",
]
koin = [
    "koinCompose",
]
ktor = [
    "ktorAuth",
    "ktorContentNegotiation",
    "ktorCore",
    "ktorKotlinSerialization",
    "ktorLogging",
    "ktorOkhttp",
]
playReview = [
    "playReview",
    "playReviewKtx",
]
playUpdate = [
    "playUpdate",
    "playUpdateKtx",
]
room = [
    "roomKtx",
    "roomRuntime",
    "sqlCipher",
]
viewModel = [
    "lifecycle",
    "lifecycleCompose",
    "lifecycleComposeRuntime",
    "lifecycleLifecycle",
    "lifecycleProcess",
    "lifecycleSavedstate",
]

[plugins]
agpApplication = { id = "com.android.application", version.ref = "agp" }
agpLibrary = { id = "com.android.library", version.ref = "agp" }
gradleVersions = "com.github.ben-manes.versions:0.47.0"
kotlinAndroid = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlinKapt = { id = "org.jetbrains.kotlin.kapt", version.ref = "kotlin" }
kotlinParcelize = { id = "org.jetbrains.kotlin.plugin.parcelize", version.ref = "kotlin" }
kotlinSerialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "kotlinKsp" }
protobuf = "com.google.protobuf:0.9.1"
twofasAndroidApplication = "twofas.androidApplication:unspecified"
twofasAndroidLibrary = "twofas.androidLibrary:unspecified"
twofasCompose = "twofas.compose:unspecified"
versionCatalogUpdate = "nl.littlerobots.version-catalog-update:0.8.1"
